INSERT INTO users (username, password)
VALUES
('divya', 'password123'),
('lily', 'password321'),
('minahil', 'password098');

DROP TABLE full_data IF EXISTS;
CREATE TABLE  full_data  AS SELECT * FROM CSVREAD('db-bonds-data.csv');

INSERT INTO BOOK(NAME)
SELECT BOOK_NAME FROM full_data;

INSERT INTO counterparty(NAME)
select bond_holder from full_data;

INSERT INTO security(ISIN, CUSIP, ISSUER_NAME, MATURITY_DATE, COUPON, TYPE, FACE_VALUE, CURRENCY, STATUS)
select ISIN, CUSIP, ISSUER_NAME, PARSEDATETIME(BOND_MATURITY_DATE,'dd/MM/yyyy'), COUPON_PERCENT, TYPE, FACE_VALUE, TRADE_CURRENCY, TRADE_STATUS  FROM full_data;

INSERT INTO TRADES(BOOK_ID,SECURITY_ID, COUNTERPARTY_ID, CURRENCY, STATUS, QUANTITY,UNIT_PRICE,BUY_SELL,TRADE_DATE,SETTLEMENT_DATE)
select BOOK.ID AS BOOK_ID,SECURITY.ID AS SECURITY_ID,COUNTERPARTY.ID AS COUNTERPARTY_ID,SECURITY.CURRENCY AS CURRENCY,SECURITY.STATUS AS STATUS,FULL_DATA.QUANTITY AS QUANTITY,FULL_DATA.UNIT_PRICE AS UNIT_PRICE,FULL_DATA.TRADE_TYPE AS BUY_SELL,FULL_DATA.TRADE_DATE AS TRADE_DATE, FULL_DATA.BOND_MATURITY_DATE AS SETTLEMENT_DATE
 FROM SECURITY
JOIN BOOK ON SECURITY.ID = BOOK.ID
JOIN COUNTERPARTY ON COUNTERPARTY.ID=SECURITY.ID
JOIN FULL_DATA ON FULL_DATA.TYPE=SECURITY.TYPE;
